### PR TITLE
ApplyUpgrade: register ResStockArguments runner results to main runner

### LINKED ISSUE #1287: ApplyUpgrade can fail silently
Before adding [this commit](https://github.com/NREL/resstock/pull/1254/commits/8a0c0a73866de01d56d2d5bd224be0fa6e3833ad) on https://github.com/NREL/resstock/pull/1254, ResStockArguments was failing and causing ApplyUpgrade to preemptively return (as successful but without writing an upgraded.xml file): https://github.com/NREL/resstock/blob/develop/measures/ApplyUpgrade/measure.rb#L299-L301

We need to update ApplyUpgrade (and maybe BuildExistingModel) to fail if ResStockArguments fails.

This may be true for any measure that the BuildExistingModel and ApplyUpgrade meta measures call, not just ResStockArguments.

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Closes #1287.

## Checklist

Not all may apply:

- [ ] Tests (and test files) have been updated
- [ ] Documentation has been updated
  - [ ] If related to resstock-estimation, checklist includes [data dictionary](https://github.com/NREL/resstock/tree/develop/resources/data/dictionary), [source report](https://github.com/NREL/resstock/tree/develop/project_national/resources/source_report.csv), [options saturation](https://github.com/NREL/resstock/tree/develop/project_national/resources/options_saturations.csv), [options_lookup](https://github.com/NREL/resstock/blob/develop/resources/options_lookup.tsv).
- [ ] Add to the [changelog_dev.rst file](https://github.com/NREL/resstock/tree/develop/docs/read_the_docs/source/changelog/changelog_dev.rst)
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected regression test changes on CI (checked comparison artifacts)

### CODE REVIEW

File: measures/ApplyUpgrade/measure.rb [hunk 1]
```diff
@@ -297,6 +297,7 @@ def run(model, runner, user_arguments)
 
       # Run the ResStockArguments measure
       if not apply_measures(measures_dir, { 'ResStockArguments' => measures['ResStockArguments'] }, resstock_arguments_runner, model, true, 'OpenStudio::Measure::ModelMeasure', 'upgraded.osw')
+        register_logs(runner, resstock_arguments_runner)
```
Comment (joseph-robertson) [inline measures/ApplyUpgrade/measure.rb:300]: Returning false without any registered errors won't stop the workflow.
