### PR TITLE
Typo for square feet area of multi-family

### LINKED ISSUE #1114: Typo for square feet area of multi-family (33171 needs to be reduced an order of magnitude)
https://github.com/NREL/resstock/blob/develop/measures/ResStockArguments/measure.rb#L401

This shows square footage for an MF housing bin of 3000-3999 to be 33171. I assume this is incorrect and a typo, but should be a quick fix.

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Closes #1114.

CI results show that this affects only a handful of testing project datapoints, and no national project datapoints.

## Checklist

Not all may apply:

- [ ] Tests (and test files) have been updated
- [ ] Documentation has been updated
  - [ ] If related to resstock-estimation, checklist includes data dictionary, source report, options_lookup
- [ ] Changelog has been updated
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected regression test changes on CI (checked comparison artifacts)

### CODE REVIEW

File: measures/ResStockArguments/measure.rb [hunk 1]
```diff
@@ -398,7 +398,7 @@ def run(model, runner, user_arguments)
                ['2500-2999', HPXML::ResidentialTypeApartment] => 2648, # AHS 2021, multi-family weighted average
                ['3000-3999', HPXML::ResidentialTypeSFD] => 3310, # AHS 2021, 1 detached and mobile home weighted average
                ['3000-3999', HPXML::ResidentialTypeSFA] => 3228, # AHS 2021, 1 attached
-               ['3000-3999', HPXML::ResidentialTypeApartment] => 33171, # AHS 2021, multi-family weighted average
+               ['3000-3999', HPXML::ResidentialTypeApartment] => 3317, # AHS 2021, multi-family weighted average
```
Comment (joseph-robertson) [inline measures/ResStockArguments/measure.rb:401]: What should this value actually be?
