### PR TITLE
Split out Other and TV plug loads

### LINKED ISSUE #1206: Split out TVs and other technologies from Plug Loads
Plug loads are often really large in the results and are not actionable. One piece is TVs that could be split out. I also think humidifiers are lumped into plug loads. 

We would need to update some TSVs, and the plug load regressions.

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Closes #1206.
Companion PR: https://github.com/NREL/resstock-estimation/pull/401.

This PR takes the RECS 2020 MLR results from the companion PR, and "plugs" them into ResStockArguments:

**Single-Family Detached**
Other = 863.26 + 219.26 * noccs + 0.33 * cfa

**Single-Family Attached**
Other = 654.92 + 206.52 * noccs + 0.21 * cfa

**Apartment**
Other = 706.6 + 149.27 * noccs + 0.1 * cfa

For TV, we are now using OS-HPXML defaults (i.e., TV = 413.0 + 69.0 * NumberofBedrooms based on ANSI/RESNET/ICC 301-2019, where NumberofBedrooms is adjusted based on NumberofResidents).

image
image
image

## Checklist

Not all may apply:

- [x] Tests (and test files) have been updated
- [x] Documentation has been updated
  - [x] If related to resstock-estimation, checklist includes [data dictionary](https://github.com/NREL/resstock/tree/develop/resources/data/dictionary), [source report](https://github.com/NREL/resstock/tree/develop/project_national/resources/source_report.csv), [options saturation](https://github.com/NREL/resstock/tree/develop/project_national/resources/options_saturations.csv), [options_lookup](https://github.com/NREL/resstock/blob/develop/resources/options_lookup.tsv).
- [x] Changelog has been updated
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected regression test changes on CI (checked comparison artifacts)

### CODE REVIEW

File: measures/ResStockArguments/measure.rb [hunk 1]
```diff
@@ -452,19 +458,30 @@ def run(model, runner, user_arguments)
...
 
+    # Television
+    if args[:misc_plug_loads_television_annual_kwh].to_s == Constants.Auto
+      if [HPXML::ResidentialTypeSFD].include?(args[:geometry_unit_type])
+        args[:misc_plug_loads_television_annual_kwh] = 309.9 + 96.11 * args[:geometry_unit_num_occupants] + 0.06 * args[:geometry_unit_cfa] # RECS 2020
+      elsif [HPXML::ResidentialTypeSFA].include?(args[:geometry_unit_type])
+        args[:misc_plug_loads_television_annual_kwh] = 272.66 + 74.16 * args[:geometry_unit_num_occupants] + 0.08 * args[:geometry_unit_cfa] # RECS 2020
+      elsif [HPXML::ResidentialTypeApartment].include?(args[:geometry_unit_type])
+        args[:misc_plug_loads_television_annual_kwh] = 171.97 + 76.09 * args[:geometry_unit_num_occupants] + 0.11 * args[:geometry_unit_cfa] # RECS 2020
+      end
```
Comment (joseph-robertson) [inline measures/ResStockArguments/measure.rb:474]: CFA may have a weak correlation here. Consider replacing with some combination of:
* no replacement (number of occupants only)
* number of bedrooms
* number of TVs

(OS-HPXML "TV other" default is calculated based on number of bedrooms.)

Comment (joseph-robertson) [reply measures/ResStockArguments/measure.rb]: Going with number of occupants and number of TVs.
