### PR TITLE
Reduce garage protrusion slightly for 0-499 Geometry Floor Area

### LINKED ISSUE #1255: Error: Garage is as wide as the single-family detached unit
Currently, it's possible in the national project to throw this error when the following combination of parameter/options is sampled:
* Geometry Building Type RECS = Single-Family Detached
* Geometry Floor Area = 0-499
* Geometry Stories = 2
* Geometry Garage = 1 Car

Garage width is 12 ft whereas the width of the building is 11.7 ft.

Possible solutions:
* reduce `geometry_garage_protrusion` to a value less than 0.75? Looks like 0.7 would work (building width becomes 12.3 ft).
* for 1 car garages, either:
  * reduce `geometry_garage_width` from 12 ft to 11 ft, or
  * reduce `geometry_garage_depth` from 24 ft to 22 ft?

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Closes #1255.

With `geometry_garage_protrusion=0.75` => "Garage is as wide as the single-family detached unit."
With `geometry_garage_protrusion=0.7` => "Garage is as deep as the single-family detached unit."
With `geometry_garage_protrusion=0.72` => No error.

Add a new `test_create_geometry_envelope` test to the ResStockArguments test file for running OS-HPXML's `create_geometry_envelope` on the 10K datapoints from the national project. This test will catch any future issues like the one this PR fixes. **10K datapoints adds about 30 minutes to the overall CI runtime, but a random 80% from that same 10K is pretty even.**

## Checklist

Not all may apply:

- [x] Tests (and test files) have been updated
- [x] Documentation has been updated
  - [x] If related to resstock-estimation, checklist includes [data dictionary](https://github.com/NREL/resstock/tree/develop/resources/data/dictionary), [source report](https://github.com/NREL/resstock/tree/develop/project_national/resources/source_report.csv), [options saturation](https://github.com/NREL/resstock/tree/develop/project_national/resources/options_saturations.csv), [options_lookup](https://github.com/NREL/resstock/blob/develop/resources/options_lookup.tsv).
- [x] Add to the [changelog_dev.rst file](https://github.com/NREL/resstock/tree/develop/docs/read_the_docs/source/changelog/changelog_dev.rst)
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected regression test changes on CI (checked comparison artifacts)

### CODE REVIEW

File: resources/buildstock.rb [hunk 1]
```diff
@@ -247,25 +247,6 @@ def get_value_from_workflow_step_value(step_value)
   end
 end
 
-def get_values_from_runner_past_results(runner, measure_name)
```
Comment (joseph-robertson) [inline resources/buildstock.rb:250]: I don't believe this is being used anywhere.

File: .github/workflows/config.yml [hunk 2]
```diff
@@ -78,6 +74,24 @@ jobs:
...
+        with:
+          ref: ${{ github.head_ref }}
+
+      - name: Install gems
+        run: |
+          rm -f Gemfile.lock && bundle install
+
+      - name: Run all measure tests
+        run: |
+          bundle exec rake workflow:measure_tests
```
Comment (joseph-robertson) [inline .github/workflows/config.yml:93]: Move measure_tests into its own namespace and job.

File: measures/ResStockArguments/tests/resstock_arguments_test.rb [hunk 3]
```diff
@@ -35,4 +39,125 @@ def test_options_lookup_assignment
     puts "resstock_arguments - lookup_arguments: #{resstock_arguments_extras.sort}" if !resstock_arguments_extras.empty?
     assert_equal(0, resstock_arguments_extras.size)
   end
+
+  def test_create_geometry_envelope
+    characteristics_dir = File.join(File.dirname(__FILE__), '../../../project_national/housing_characteristics')
+    parameters_ordered = get_parameters_ordered_from_options_lookup_tsv(@lookup_csv_data, characteristics_dir)
+    measures_dir = File.join(File.dirname(__FILE__), '../../../measures')
+    parameter_options_measure_args = _get_parameter_options_measure_args(@lookup_csv_data)
```
Comment (joseph-robertson) [inline measures/ResStockArguments/tests/resstock_arguments_test.rb:47]: Do this operate once ahead of the loop through 10K datapoints -- much faster than calling `get_measure_args_from_option_names` for every datapoint.

File: resources/options_lookup.tsv [hunk 4]
```diff
@@ -9366,7 +9366,7 @@ Geometry Building Type RECS	Multi-Family with 2 - 4 Units	ResStockArguments	geom
 Geometry Building Type RECS	Multi-Family with 5+ Units	ResStockArguments	geometry_unit_type=apartment unit	geometry_average_ceiling_height=8	geometry_unit_aspect_ratio=0.5556
 Geometry Building Type RECS	Single-Family Attached	ResStockArguments	geometry_unit_type=single-family attached	geometry_average_ceiling_height=8	geometry_unit_aspect_ratio=0.5556
 Geometry Building Type RECS	Single-Family Detached	ResStockArguments	geometry_unit_type=single-family detached	geometry_average_ceiling_height=8	geometry_unit_aspect_ratio=1.8
-Geometry Floor Area	0-499	ResStockArguments	geometry_unit_cfa_bin=0-499	geometry_unit_cfa=auto	geometry_garage_protrusion=0.75
+Geometry Floor Area	0-499	ResStockArguments	geometry_unit_cfa_bin=0-499	geometry_unit_cfa=auto	geometry_garage_protrusion=0.72
```
Comment (joseph-robertson) [inline resources/options_lookup.tsv:9369]: This is the actual fix here.

File: .github/workflows/config.yml (hunk 2 above)
Comment (afontani) [reply .github/workflows/config.yml:93]: @joseph-robertson : This new test increases the CI time by about 27 minutes. I take it that is just because we used 10k samples? Is it worth reducing the sample size slightly?

Comment (joseph-robertson) [reply .github/workflows/config.yml:93]: We could. Perhaps pick a random 5K subset from the already-sampled 10K set? Something like that?

Comment (joseph-robertson) [reply .github/workflows/config.yml:93]: @afontani I tried running 8K out of the 10K (random seeded 80%), and the resulting CI runtime seems to not add much extra, if any, overall runtime. Let me know what you think.

**Review by afontani — APPROVED** [review]
Thanks for reducing the CI time.
